import Footer from "./Footer"

const Terms = () => {
    return (
        <>
            <div className="preload preload-container">
                <div className="preload-logo"></div>
            </div>

            <div id="wrapper" className="wrapper-style">
                <div id="page" className="clearfix">

                    {/* <Header />
                    <Slider /> */}
                    <section id="collection" className=" tf-collection ">
                        <div className="tf-container">
                            <div className="row">

                                <div className="tf-heading mb60 wow fadeInUp" style={{ textAlign: 'justify' }}>
                                    <h2 className="heading tc-heading text-center">TERMS &amp; CONDITIONS</h2>
                                    <p className="spacing">This website is owned and operated by Club Virtual Pty Ltd (ACN 653 514 231), which is the owner of the Leafers concept, design and all associated intellectual property (“IP”) including the domain name leafers.io. Throughout the site, the term "we", "us", “our”, “Company", “Leafers”, “leafers.io”, “CV” as the context may require, refer to Club Virtual Pty Ltd. By visiting our site and/or purchasing something from us, you engage in our service (“Service”) and agree to be bound by the following terms and conditions (“Terms”).</p>
                                    <br />
                                    <p className="spacing">We reserve the right to update, change or replace any part of these Terms of services without prior written notice at any time, and it is your responsibility to periodically review these Terms to stay informed of updates. Any changes to the Terms will be in effect as of the last updated referenced on the site and at the top of these Terms.</p>
                                    <p className="spacing">Your continued use of this site after the last updated date will constitute your acceptance of agreement.</p>
                                    <br />
                                    <p className="spacing">By visiting the website of our products merchants, in particular www.opensea.io or clubvirtual.io as the case may be, you also engage and agree to be bound by their terms and conditions.</p>
                                    <p className="spacing">This website is for informational purposes and serves as a binding contract for purchasers of Leafers NFTs.</p>
                                    <br />
                                    <p className="spacing">Leafers is a generative collection of digital artwork (NFTs) housed and run on the Binance Smart Chain Network. Users and collector of these NFTs are solely responsible for the safety and the management of their own private assets, which include but are not limited to Binance Smart Chain wallets, validating all transactions and contracts generated by this website prior to and after purchases.</p>
                                    <p className="spacing">Users certify through purchase that they understand that, as the Leafers smart contract runs on the Binance Smart Chain network and is bound by their system and terms, there is no ability to undo, reverse, or restore any transactions.</p>
                                    <p className="spacing">Any connected services included this website are provided “as is” and “as available” without any warranty of any kind. Use of this website constitutes your agreement that you are accepting sole responsibility for any and all transactions involving Leafers digital collectibles.</p>
                                    <br />
                                    <p className="spacing">By agreeing to these Terms, you represent that you are at least the age of majority in your state or province of residence.</p>
                                    <br />
                                    <p className="spacing">You may not use our products and/or services for any illegal or unauthorized purpose nor may you, in the use of the Service, violate any laws in your jurisdiction (including but not limited to copyright laws).</p>
                                    <br />
                                    <h3 className="pad-top-20">Ownership, usage &amp; IP</h3>

                                    <p className="spacing">When you purchase your Leafers NFT, you own the NFT. The ownership is transferred to you on the Binance Smart Chain blockchain for that individual piece of art, combination of traits and number. Ownership of the NFT is ruled by the smart contract and the Binance Smart Chain Network terms. We have no ability to alter, freeze, seize or modify the ownership of any Leafers NFT.</p>
                                    <br />
                                    <p className="spacing">All buyers acknowledge and agree that, following the purchase of any Leafers NFT on the website, they do not have any legal ownership right, or title to any copyrights, trademarks or other intellectual property rights to the underlying artwork of the Leafers NFT.  All copyrights and intellectual property rights in the underlying artwork shall remain vested in CV, including but not limited to the right to reproduce, to prepare derivative works, to display, to perform and to distribute the artworks.</p>
                                    <br />
                                    <p className="spacing">Following the purchase of a Leafers NFT on the website, the buyer may display or perform the Leafers NFT publicly or privately for the purposes of promoting, sharing, discussing or commenting on the buyer’s purchase, ownership or interest in the Leafers NFT.</p>
                                    <br />
                                    <p className="spacing">The buyer of the Leafers NFT may display or perform the NFT on:</p>

                                    <p className="spacing">(a) third party platforms in association with an offer to sell or trade the NFT; and</p>
                                    <p className="spacing">(b)	within decentralised virtual environments (including other NFT marketplaces, virtual or physical galleries and virtual or physical museums).</p>
                                    <br />
                                    <p className="spacing" >The buyer acknowledges and agrees that it may not, nor permit any third party, without the prior written consent of CV:</p>
                                    <p className="spacing">(a)	make “commercial use” of any underlying artwork to the NFT including by selling the copies of, access to the artwork or otherwise commercially exploiting the artwork;</p>

                                    <p className="spacing">(b)	modify, distort or modify the artwork in a way which would be prejudicial to the Artist’s interests;</p>
                                    <p className="spacing">(c)	use the artwork to advertise, market or sell any third-party product or service;</p>
                                    <p className="spacing">(d)	use the artwork in connection with any form of media that depicts hatred, intolerance, violence, cruelty or anything else that may be considered hate speech;</p>
                                    <p className="spacing">(e)	sell, distribute for commercial gain, or otherwise commercialise merchandise that includes the artwork;</p>
                                    <p className="spacing">(f)	attempt to trademark, copyright or otherwise acquire additional intellectual property rights in or to the artwork;</p>
                                    <p className="spacing">(g)	attempt to mint an NFT representing the same artwork; and </p>
                                    <p className="spacing">(h)	falsify, misrepresent, or conceal the ownership of the artwork or the NFT. </p>
                                    <br />
                                    <h3 className="pad-top-20" >Feedback</h3>
                                    <p className="spacing">You can submit comments, bug reports, ideas about the site or the project. By submitting any feedback, you agree that we are free to use them in any way we choose without additional compensation to you and you hereby grant us a perpetual, irrevocable, nonexclusive worldwide licence to incorporate and use the feedback for any purpose.</p>



                                </div>
                            </div>
                        </div>
                        <div style={{display:'flex', justifyContent:'center'}}>
                            <a href='/'>Back</a>
                        </div>
                    </section>
                    <Footer />
                </div>
            </div>

            <a id="scroll-top"></a>
        </>
    )
}

export default Terms